name: datetime_picker_formfield
description: A Flutter widget that wraps a TextFormField and integrates the date and/or time picker dialogs.
version: 0.1.6
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/datetime_picker_formfield

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.1.2 <2.0.0"