name: datetime_picker_formfield
description: A TextFormField that emits DateTimes and helps show Material, Cupertino, and other style picker dialogs.
version: 2.0.0
homepage: https://github.com/jifalops/datetime_picker_formfield

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <1.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 < 3.0.0'
